Add WinAppSdk Trimming support
unoplatform/uno.templates pull request #298
Opened 2023-09-18 16:58 UTC by dansiegel

GitHub Issue (If applicable): closes #

- close #241 

## PR Type

What kind of change does this PR introduce?

- Feature

## What is the current behavior?

WinAppSdk trimming is not enabled

## What is the new behavior?

WinAppSdk trimming is enabled

2023-09-18 18:10 UTC, jeromelaban approved these changes

2023-09-18 19:57 UTC, nickrandolph commented
I think publishtrimmed should be in the publish XML files.

2023-09-19 09:40 UTC, nickrandolph requested changes
PublishTrimmed should either be here or in the .pubxml files. Also not sure whether there's still work to be done to ensure trimming works for Uno apps (see https://github.com/microsoft/CsWinRT/issues/373)

2023-09-20 08:05 UTC, merged

2023-09-20 09:13 UTC, nickrandolph commented
@mergify backport legacy/4x release/stable/4.10